# frozen_string_literal: true

class TablesController < ApplicationController
  TABLES = [
    {
      name: "recording_studio_ai_runs",
      purpose: "One row per high-level AI operation. Tracks routing, attribution, lifecycle, usage, cost, and sanitized failure context.",
      columns: [
        { name: "id", type: "bigint", sample: "12041", explanation: "Primary key used as the durable identity for a run." },
        { name: "operation", type: "string", sample: "generation", explanation: "Operation category such as generation, stream, or batch." },
        { name: "purpose", type: "string", sample: "summarize_page", explanation: "Host-defined business intent that explains why the call happened." },
        { name: "status", type: "string", sample: "completed", explanation: "Execution state used by orchestration and admin reporting." },
        { name: "profile_key", type: "string", sample: "medium", explanation: "Routing profile used to select candidate providers and models." },
        { name: "requested_provider", type: "string", sample: "openai", explanation: "Provider requested by caller input, if any." },
        { name: "resolved_provider", type: "string", sample: "gemini", explanation: "Provider that actually executed after resolution and fallback rules." },
        { name: "resolved_model", type: "string", sample: "gemini-2.5-pro", explanation: "Model finally selected for execution." },
        { name: "root_recording_id", type: "bigint", sample: "904", explanation: "Root recording boundary used for tenant-safe attribution." },
        { name: "context_recording_id", type: "bigint", sample: "925", explanation: "Optional narrower context recording within the same root." },
        { name: "initiator_type", type: "string", sample: "User", explanation: "Class name for who initiated the operation." },
        { name: "initiator_id", type: "string", sample: "51", explanation: "Identifier of the initiating actor in string form." },
        { name: "initiator_kind", type: "string", sample: "user", explanation: "Normalized actor kind for analytics and policy checks." },
        { name: "initiator_snapshot", type: "json", sample: '{"label":"user-51"}', explanation: "Sanitized snapshot of initiator attributes captured at execution time." },
        { name: "executor_type", type: "string", sample: "User", explanation: "Class name of the effective executor, which can differ from initiator." },
        { name: "executor_id", type: "string", sample: "7", explanation: "Identifier of the effective executor." },
        { name: "executor_kind", type: "string", sample: "admin", explanation: "Normalized executor category." },
        { name: "executor_snapshot", type: "json", sample: '{"label":"admin-7"}', explanation: "Sanitized executor context for auditing and attribution trails." },
        { name: "impersonator_type", type: "string", sample: "User", explanation: "Actor class that initiated impersonation, if impersonation is active." },
        { name: "impersonator_id", type: "string", sample: "3", explanation: "Identifier of impersonating actor." },
        { name: "impersonator_snapshot", type: "json", sample: '{"label":"owner-3"}', explanation: "Snapshot of impersonation context used for audit reconstruction." },
        { name: "execution_source", type: "string", sample: "job", explanation: "Execution origin such as request cycle, background job, or console." },
        { name: "request_id", type: "string", sample: "8d8c2a8d-4dce-4dfa-a49f-8e2f52372f7b", explanation: "Rack or host request identifier for trace correlation." },
        { name: "job_id", type: "string", sample: "e73aefb2-7d00-4c68-9fbd-2b0b2eb0f6d3", explanation: "Background job identifier when run asynchronously." },
        { name: "started_at", type: "datetime", sample: "2026-08-12T06:31:00Z", explanation: "Timestamp when execution started." },
        { name: "completed_at", type: "datetime", sample: "2026-08-12T06:31:03Z", explanation: "Timestamp when execution reached terminal state." },
        { name: "latency_ms", type: "bigint", sample: "3102", explanation: "End-to-end duration in milliseconds used for SLO and warning metrics." },
        { name: "input_tokens", type: "bigint", sample: "920", explanation: "Total input tokens aggregated across attempts." },
        { name: "output_tokens", type: "bigint", sample: "264", explanation: "Total output tokens aggregated across attempts." },
        { name: "total_tokens", type: "bigint", sample: "1184", explanation: "Provider-reported or derived total token count." },
        { name: "cached_input_tokens", type: "bigint", sample: "120", explanation: "Input tokens served from provider cache when supported." },
        { name: "reasoning_tokens", type: "bigint", sample: "48", explanation: "Reasoning-token usage for providers that expose it." },
        { name: "cost_amount_microunits", type: "bigint", sample: "1840000", explanation: "Monetary cost expressed in microunits for precision-safe aggregation." },
        { name: "cost_currency", type: "string", sample: "USD", explanation: "Currency for the aggregated run cost." },
        { name: "cost_estimated", type: "boolean", sample: "false", explanation: "Indicates whether cost came from provider billing or an estimate/catalog." },
        { name: "attempt_count", type: "integer", sample: "2", explanation: "Number of attempts created under this run." },
        { name: "retry_count", type: "integer", sample: "1", explanation: "Number of retry attempts for the same candidate." },
        { name: "fallback_count", type: "integer", sample: "1", explanation: "Number of fallback hops between candidates or profiles." },
        { name: "custom_tool_invocation_count", type: "integer", sample: "3", explanation: "How many custom-tool invocations occurred in this run." },
        { name: "input_digest", type: "string", sample: "22f1a42f...", explanation: "Digest of input content for integrity and duplicate analysis without persisting raw prompts." },
        { name: "output_digest", type: "string", sample: "7f2f8b19...", explanation: "Digest of assembled output content." },
        { name: "input_character_count", type: "integer", sample: "4021", explanation: "Input character volume indicator for cost and retention heuristics." },
        { name: "output_character_count", type: "integer", sample: "1033", explanation: "Output character volume indicator." },
        { name: "attachment_count", type: "integer", sample: "2", explanation: "Number of attachments accepted for this run." },
        { name: "attachment_total_bytes", type: "bigint", sample: "458223", explanation: "Total attachment payload size used for limits and observability." },
        { name: "attachment_content_types", type: "json", sample: '["application/pdf","image/png"]', explanation: "Content-type inventory for accepted attachments." },
        { name: "citation_count", type: "integer", sample: "4", explanation: "Count of citations produced across attempts." },
        { name: "web_search_requested", type: "boolean", sample: "true", explanation: "Whether request asked for provider-native web search tools." },
        { name: "web_search_used", type: "boolean", sample: "true", explanation: "Whether provider output indicates web search usage." },
        { name: "error_category", type: "string", sample: "timeout", explanation: "Normalized failure category when run fails." },
        { name: "error_code", type: "string", sample: "provider_timeout", explanation: "More specific normalized error code." },
        { name: "error_message", type: "string", sample: "Provider request timed out.", explanation: "Safe, normalized message suitable for logs and admin UI." },
        { name: "metadata", type: "json", sample: '{"feature":"editor"}', explanation: "Sanitized host metadata propagated into execution history." },
        { name: "lock_version", type: "integer", sample: "5", explanation: "Optimistic locking version used to guard concurrent updates." },
        { name: "created_at", type: "datetime", sample: "2026-08-12T06:31:00Z", explanation: "Row creation timestamp." },
        { name: "updated_at", type: "datetime", sample: "2026-08-12T06:31:03Z", explanation: "Last mutation timestamp." }
      ]
    },
    {
      name: "recording_studio_ai_attempts",
      purpose: "Per-candidate execution records under a run. Captures retries/fallbacks, provider metrics, and terminal outcomes.",
      columns: [
        { name: "id", type: "bigint", sample: "38192", explanation: "Primary key for the attempt." },
        { name: "run_id", type: "bigint", sample: "12041", explanation: "Parent run that owns this attempt." },
        { name: "sequence", type: "integer", sample: "2", explanation: "1-based attempt order inside the run." },
        { name: "kind", type: "string", sample: "retry", explanation: "Attempt role such as primary, retry, fallback, or continuation." },
        { name: "status", type: "string", sample: "completed", explanation: "Lifecycle state for this attempt." },
        { name: "profile_key", type: "string", sample: "medium", explanation: "Profile context used when this attempt executed." },
        { name: "provider", type: "string", sample: "openai", explanation: "Provider selected for this specific attempt." },
        { name: "model", type: "string", sample: "gpt-5", explanation: "Model selected for this attempt." },
        { name: "provider_request_id", type: "string", sample: "resp_abc123", explanation: "Provider-side request identifier for diagnostics." },
        { name: "streaming", type: "boolean", sample: "false", explanation: "True when attempt used streaming semantics." },
        { name: "started_at", type: "datetime", sample: "2026-08-12T06:31:00Z", explanation: "Attempt start time." },
        { name: "completed_at", type: "datetime", sample: "2026-08-12T06:31:01Z", explanation: "Attempt terminal time." },
        { name: "latency_ms", type: "bigint", sample: "922", explanation: "Attempt duration in milliseconds." },
        { name: "input_tokens", type: "bigint", sample: "460", explanation: "Input token count for this attempt." },
        { name: "output_tokens", type: "bigint", sample: "132", explanation: "Output token count for this attempt." },
        { name: "total_tokens", type: "bigint", sample: "592", explanation: "Total token count for this attempt." },
        { name: "cached_input_tokens", type: "bigint", sample: "60", explanation: "Cached input token count for this attempt." },
        { name: "reasoning_tokens", type: "bigint", sample: "24", explanation: "Reasoning token count when available." },
        { name: "cost_amount_microunits", type: "bigint", sample: "920000", explanation: "Attempt-level cost in microunits." },
        { name: "cost_currency", type: "string", sample: "USD", explanation: "Currency for attempt cost." },
        { name: "cost_estimated", type: "boolean", sample: "false", explanation: "Whether attempt cost is estimated." },
        { name: "cost_source", type: "string", sample: "provider", explanation: "Origin of cost value, for example provider or catalog." },
        { name: "finish_reason", type: "string", sample: "stop", explanation: "Provider finish reason for model output termination." },
        { name: "retryable", type: "boolean", sample: "false", explanation: "Whether failure, if present, was classified as retryable." },
        { name: "web_search_requested", type: "boolean", sample: "true", explanation: "Whether native search tool usage was requested." },
        { name: "web_search_used", type: "boolean", sample: "true", explanation: "Whether native search evidence appeared in output." },
        { name: "citation_count", type: "integer", sample: "2", explanation: "Citations produced by this attempt." },
        { name: "attachment_count", type: "integer", sample: "1", explanation: "Attachment count consumed by this attempt." },
        { name: "attachment_total_bytes", type: "bigint", sample: "133120", explanation: "Total attachment bytes for this attempt." },
        { name: "attachment_content_types", type: "json", sample: '["application/pdf"]', explanation: "Attachment MIME types used by this attempt." },
        { name: "provider_file_count", type: "integer", sample: "1", explanation: "Number of provider-hosted file objects referenced during execution." },
        { name: "error_category", type: "string", sample: "rate_limit", explanation: "Normalized failure category at attempt granularity." },
        { name: "error_code", type: "string", sample: "http_429", explanation: "Specific normalized failure code." },
        { name: "error_message", type: "string", sample: "Provider rate limit exceeded.", explanation: "Sanitized error message." },
        { name: "metadata", type: "json", sample: '{"tier":"paid"}', explanation: "Sanitized metadata captured for this attempt." },
        { name: "lock_version", type: "integer", sample: "2", explanation: "Optimistic lock counter for concurrency safety." },
        { name: "created_at", type: "datetime", sample: "2026-08-12T06:31:00Z", explanation: "Row creation timestamp." },
        { name: "updated_at", type: "datetime", sample: "2026-08-12T06:31:01Z", explanation: "Last update timestamp." }
      ]
    },
    {
      name: "recording_studio_ai_custom_tool_invocations",
      purpose: "Tracks every tool call requested by providers, including confirmation flow, execution outcome, and sanitized summaries.",
      columns: [
        { name: "id", type: "bigint", sample: "991", explanation: "Primary key for tool invocation." },
        { name: "run_id", type: "bigint", sample: "12041", explanation: "Parent run that owns the tool invocation." },
        { name: "requested_by_attempt_id", type: "bigint", sample: "38191", explanation: "Attempt that requested the tool call." },
        { name: "continued_by_attempt_id", type: "bigint", sample: "38192", explanation: "Follow-up attempt that consumed tool result and continued generation." },
        { name: "provider_tool_call_id", type: "string", sample: "call_7z8x", explanation: "Provider-origin call identifier used to match tool results." },
        { name: "tool_key", type: "string", sample: "summarize_record", explanation: "Stable key of registered tool definition." },
        { name: "tool_version", type: "integer", sample: "1", explanation: "Tool contract version requested by model." },
        { name: "tool_name_snapshot", type: "string", sample: "Summarize Record", explanation: "Human-readable tool name snapshot for reporting." },
        { name: "status", type: "string", sample: "completed", explanation: "Invocation lifecycle state from requested to terminal." },
        { name: "read_only", type: "boolean", sample: "true", explanation: "Tool capability flag indicating no side effects." },
        { name: "destructive", type: "boolean", sample: "false", explanation: "Tool capability flag indicating potentially destructive actions." },
        { name: "requires_confirmation", type: "boolean", sample: "true", explanation: "Whether invocation must be explicitly confirmed." },
        { name: "idempotent", type: "boolean", sample: "true", explanation: "Whether repeated execution is expected to be safe and equivalent." },
        { name: "cost_category", type: "string", sample: "low", explanation: "Declared cost class used for policy and operator awareness." },
        { name: "latency_category", type: "string", sample: "fast", explanation: "Declared latency class used for expectations and UX decisions." },
        { name: "confirmation_status", type: "string", sample: "confirmed", explanation: "Confirmation state for tools requiring approval." },
        { name: "confirmed_by_type", type: "string", sample: "User", explanation: "Actor class that approved execution." },
        { name: "confirmed_by_id", type: "string", sample: "7", explanation: "Identifier of actor that approved execution." },
        { name: "confirmed_at", type: "datetime", sample: "2026-08-12T06:31:01Z", explanation: "Timestamp when confirmation was granted." },
        { name: "arguments_digest", type: "string", sample: "bc7a12f8...", explanation: "Digest of validated arguments for integrity without persisting raw payloads." },
        { name: "arguments_summary", type: "text", sample: "topic=Rails, format=short", explanation: "Sanitized compact summary of tool arguments." },
        { name: "result_digest", type: "string", sample: "9f72e211...", explanation: "Digest of serialized tool result." },
        { name: "result_summary", type: "text", sample: "summary generated", explanation: "Sanitized compact summary of execution result." },
        { name: "started_at", type: "datetime", sample: "2026-08-12T06:31:01Z", explanation: "Execution start timestamp for the tool call." },
        { name: "completed_at", type: "datetime", sample: "2026-08-12T06:31:01Z", explanation: "Execution completion timestamp." },
        { name: "latency_ms", type: "bigint", sample: "84", explanation: "Tool execution latency in milliseconds." },
        { name: "error_category", type: "string", sample: "custom_tool_failed", explanation: "Normalized tool failure category." },
        { name: "error_code", type: "string", sample: "tool_timeout", explanation: "Specific failure code for policy/reporting." },
        { name: "error_message", type: "string", sample: "Custom tool execution timed out.", explanation: "Safe error message describing failure at a high level." },
        { name: "metadata", type: "json", sample: '{"executor":"Topics.lookup"}', explanation: "Sanitized per-invocation metadata for observability." },
        { name: "lock_version", type: "integer", sample: "1", explanation: "Optimistic lock version." },
        { name: "created_at", type: "datetime", sample: "2026-08-12T06:31:01Z", explanation: "Row creation timestamp." },
        { name: "updated_at", type: "datetime", sample: "2026-08-12T06:31:01Z", explanation: "Last update timestamp." }
      ]
    },
    {
      name: "recording_studio_ai_batches",
      purpose: "Batch-level orchestration records for provider-native async/bulk execution, including item counts, aggregate usage, and lifecycle metadata.",
      columns: [
        { name: "id", type: "bigint", sample: "551", explanation: "Primary key for batch execution." },
        { name: "status", type: "string", sample: "processing", explanation: "Batch status from preparing through terminal outcomes." },
        { name: "profile_key", type: "string", sample: "medium", explanation: "Profile context used for batch submission." },
        { name: "provider", type: "string", sample: "openai", explanation: "Provider responsible for the batch." },
        { name: "model", type: "string", sample: "gpt-5", explanation: "Model used for batch items." },
        { name: "provider_batch_id", type: "string", sample: "batch_abc123", explanation: "Provider-side identifier for polling/cancellation." },
        { name: "root_recording_id", type: "bigint", sample: "904", explanation: "Root attribution boundary for the whole batch." },
        { name: "context_recording_id", type: "bigint", sample: "925", explanation: "Optional context attribution boundary for batch." },
        { name: "initiator_type", type: "string", sample: "User", explanation: "Class name of initiating actor." },
        { name: "initiator_id", type: "string", sample: "51", explanation: "Identifier of initiating actor." },
        { name: "initiator_kind", type: "string", sample: "user", explanation: "Normalized initiator kind." },
        { name: "initiator_snapshot", type: "json", sample: '{"label":"user-51"}', explanation: "Sanitized initiator context snapshot." },
        { name: "executor_type", type: "string", sample: "User", explanation: "Class name for effective executor." },
        { name: "executor_id", type: "string", sample: "7", explanation: "Identifier for effective executor." },
        { name: "executor_kind", type: "string", sample: "admin", explanation: "Normalized executor kind." },
        { name: "executor_snapshot", type: "json", sample: '{"label":"admin-7"}', explanation: "Sanitized executor snapshot." },
        { name: "impersonator_type", type: "string", sample: "User", explanation: "Actor class performing impersonation when applicable." },
        { name: "impersonator_id", type: "string", sample: "3", explanation: "Identifier of impersonating actor." },
        { name: "impersonator_snapshot", type: "json", sample: '{"label":"owner-3"}', explanation: "Sanitized impersonation context for audit traceability." },
        { name: "execution_source", type: "string", sample: "job", explanation: "Origin channel for batch submission." },
        { name: "request_id", type: "string", sample: "5b340845-a2a2-4ece-84ce-85ff2f0578e8", explanation: "Request correlation id when batch started from web request." },
        { name: "job_id", type: "string", sample: "2f810aa6-84f6-4a7e-9538-524fa1b5ce71", explanation: "Job id for async submission/synchronization flows." },
        { name: "item_count", type: "integer", sample: "200", explanation: "Total intended items in the batch." },
        { name: "completed_item_count", type: "integer", sample: "160", explanation: "How many items are completed." },
        { name: "failed_item_count", type: "integer", sample: "12", explanation: "How many items failed." },
        { name: "cancelled_item_count", type: "integer", sample: "3", explanation: "How many items were cancelled." },
        { name: "input_tokens", type: "bigint", sample: "63210", explanation: "Aggregate input tokens over batch items." },
        { name: "output_tokens", type: "bigint", sample: "18220", explanation: "Aggregate output tokens over batch items." },
        { name: "total_tokens", type: "bigint", sample: "81430", explanation: "Aggregate total tokens over batch items." },
        { name: "cached_input_tokens", type: "bigint", sample: "4500", explanation: "Aggregate cached input tokens when reported." },
        { name: "reasoning_tokens", type: "bigint", sample: "980", explanation: "Aggregate reasoning tokens when reported." },
        { name: "cost_amount_microunits", type: "bigint", sample: "71234000", explanation: "Aggregate cost in microunits across completed items." },
        { name: "cost_currency", type: "string", sample: "USD", explanation: "Currency for aggregated batch cost." },
        { name: "cost_estimated", type: "boolean", sample: "true", explanation: "True when cost uses catalog/estimate rather than provider billing." },
        { name: "submitted_at", type: "datetime", sample: "2026-08-12T05:50:00Z", explanation: "When provider accepted submission." },
        { name: "completed_at", type: "datetime", sample: "2026-08-12T05:58:40Z", explanation: "When batch reached a terminal state." },
        { name: "expires_at", type: "datetime", sample: "2026-08-13T05:50:00Z", explanation: "Provider or retention expiry for batch artifacts." },
        { name: "error_category", type: "string", sample: "batch_submission", explanation: "Normalized batch-level error category." },
        { name: "error_code", type: "string", sample: "batch_submission_failed", explanation: "Normalized batch-level error code." },
        { name: "error_message", type: "string", sample: "Provider batch submission failed.", explanation: "Safe message summarizing batch-level failure." },
        { name: "metadata", type: "json", sample: '{"_recording_studio_ai":{"capabilities":["provider_batch"]}}', explanation: "Sanitized metadata that preserves execution capabilities and host context." },
        { name: "lock_version", type: "integer", sample: "8", explanation: "Optimistic lock counter." },
        { name: "created_at", type: "datetime", sample: "2026-08-12T05:50:00Z", explanation: "Row creation timestamp." },
        { name: "updated_at", type: "datetime", sample: "2026-08-12T05:58:40Z", explanation: "Last mutation timestamp." }
      ]
    },
    {
      name: "recording_studio_ai_batch_items",
      purpose: "Per-item execution states and metrics for a batch. Each item also maps to exactly one run.",
      columns: [
        { name: "id", type: "bigint", sample: "90211", explanation: "Primary key for batch item." },
        { name: "batch_id", type: "bigint", sample: "551", explanation: "Parent batch identifier." },
        { name: "run_id", type: "bigint", sample: "12045", explanation: "Dedicated run linked to this batch item." },
        { name: "position", type: "integer", sample: "0", explanation: "Zero-based order of item in original request list." },
        { name: "reference", type: "string", sample: "invoice-2026-0001", explanation: "Stable caller-supplied logical reference for idempotent mapping." },
        { name: "status", type: "string", sample: "completed", explanation: "Lifecycle state for this item." },
        { name: "provider_item_id", type: "string", sample: "item_99a1", explanation: "Provider-side item identifier, if available." },
        { name: "started_at", type: "datetime", sample: "2026-08-12T05:50:10Z", explanation: "Item execution start timestamp." },
        { name: "completed_at", type: "datetime", sample: "2026-08-12T05:50:12Z", explanation: "Item execution completion timestamp." },
        { name: "input_tokens", type: "bigint", sample: "220", explanation: "Input tokens for this item." },
        { name: "output_tokens", type: "bigint", sample: "71", explanation: "Output tokens for this item." },
        { name: "total_tokens", type: "bigint", sample: "291", explanation: "Total tokens for this item." },
        { name: "cached_input_tokens", type: "bigint", sample: "18", explanation: "Cached input tokens for this item." },
        { name: "reasoning_tokens", type: "bigint", sample: "4", explanation: "Reasoning tokens for this item when available." },
        { name: "cost_amount_microunits", type: "bigint", sample: "280000", explanation: "Item-level cost in microunits." },
        { name: "cost_currency", type: "string", sample: "USD", explanation: "Currency for item-level cost." },
        { name: "cost_estimated", type: "boolean", sample: "false", explanation: "Indicates estimated vs direct item cost." },
        { name: "finish_reason", type: "string", sample: "stop", explanation: "Provider finish reason for item output." },
        { name: "error_category", type: "string", sample: "provider_error", explanation: "Normalized item-level error category." },
        { name: "error_code", type: "string", sample: "http_500", explanation: "Normalized item-level error code." },
        { name: "error_message", type: "string", sample: "Provider request failed.", explanation: "Safe item-level error message." },
        { name: "metadata", type: "json", sample: '{"structured_output":true}', explanation: "Sanitized item-specific metadata including structured-output expectations." },
        { name: "lock_version", type: "integer", sample: "3", explanation: "Optimistic lock version." },
        { name: "created_at", type: "datetime", sample: "2026-08-12T05:50:00Z", explanation: "Row creation timestamp." },
        { name: "updated_at", type: "datetime", sample: "2026-08-12T05:50:12Z", explanation: "Last update timestamp." }
      ]
    },
    {
      name: "recording_studio_ai_responses",
      purpose: "Retention table for sanitized model outputs and normalized payloads. Each response belongs to either an attempt or a batch item.",
      columns: [
        { name: "id", type: "bigint", sample: "61120", explanation: "Primary key for retained response artifact." },
        { name: "attempt_id", type: "bigint", sample: "38192", explanation: "Owner attempt for generation or stream responses." },
        { name: "batch_item_id", type: "bigint", sample: "90211", explanation: "Owner batch item for batch retention rows." },
        { name: "provider", type: "string", sample: "openai", explanation: "Provider that produced this response." },
        { name: "model", type: "string", sample: "gpt-5", explanation: "Model that produced this response." },
        { name: "provider_response_id", type: "string", sample: "resp_abc123", explanation: "Provider-side response identifier." },
        { name: "response_type", type: "string", sample: "generation", explanation: "Response category such as generation, stream, batch_item, or error." },
        { name: "raw_response", type: "text", sample: '{"id":"resp_abc123","status":"completed"}', explanation: "Sanitized allowlisted raw provider snapshot for forensic debugging." },
        { name: "normalized_response", type: "text", sample: '{"text":"Answer","citations":[]}', explanation: "Canonical normalized JSON payload used by internal readers/admin UI." },
        { name: "content_text", type: "text", sample: "Answer", explanation: "Direct assembled text for quick display without reparsing normalized JSON." },
        { name: "content_type", type: "string", sample: "application/json", explanation: "Content format classification for retained payload." },
        { name: "finish_reason", type: "string", sample: "stop", explanation: "Terminal output reason from provider semantics." },
        { name: "complete", type: "boolean", sample: "true", explanation: "Whether retention contains a complete/terminal assembled result." },
        { name: "truncated", type: "boolean", sample: "false", explanation: "Whether payload was truncated due to configured retention size limits." },
        { name: "byte_size", type: "bigint", sample: "18234", explanation: "Stored payload size for retention monitoring and cleanup." },
        { name: "expires_at", type: "datetime", sample: "2026-08-19T06:31:03Z", explanation: "Hard retention expiry timestamp used by cleanup jobs." },
        { name: "metadata", type: "json", sample: '{"retained_at":"2026-08-12T06:31:03Z"}', explanation: "Retention metadata used for cleanup, diagnostics, and observability." },
        { name: "created_at", type: "datetime", sample: "2026-08-12T06:31:03Z", explanation: "Row creation timestamp." },
        { name: "updated_at", type: "datetime", sample: "2026-08-12T06:31:03Z", explanation: "Last mutation timestamp." }
      ]
    }
  ].freeze

  def show
    @tables = TABLES.map do |table|
      schema_columns = ActiveRecord::Base.connection.columns(table[:name]).index_by(&:name)
      table.merge(
        columns: table[:columns].map do |column|
          column.merge(required: schema_columns.fetch(column[:name]).null == false)
        end
      )
    end
  end
end